# Generated by Django 3.2 on 2022-08-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20220814_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slug',
            old_name='slug',
            new_name='slug_title',
        ),
    ]
