# Generated by Django 3.2 on 2022-08-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_rename_slug_slug_slug_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
