# Generated by Django 3.2 on 2022-08-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20220815_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-order'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='slug',
            options={'verbose_name': 'Slug', 'verbose_name_plural': 'Slugs'},
        ),
    ]
