# Generated by Django 3.2 on 2022-08-08 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_rename_phone_number_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelements',
            name='price_in_order',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость в заказе'),
            preserve_default=False,
        ),
    ]
