# Generated by Django 3.2 on 2022-08-11 20:16

from django.db import migrations


def set_order_status(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    order_set = Order.objects.all()
    order_iterator = order_set.iterator()
    for order in order_iterator:
        order.status = 'UP'
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0051_auto_20220811_2316'),
    ]

    operations = [
        migrations.RunPython(set_order_status),
    ]
