# Generated by Django 3.2 on 2022-08-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_rename_price_in_order_orderelements_full_price_in_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderelements',
            old_name='full_price_in_order',
            new_name='price_in_order',
        ),
    ]
