# Generated by Django 3.2 on 2022-08-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_rename_full_price_in_order_orderelements_price_in_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-status', '-registrated_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
