# Generated by Django 3.2 on 2022-08-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UP', 'Необработанный'), ('IW', 'Готовится'), ('ID', 'Доставка'), ('DN', 'Выполнен')], db_index=True, default='UP', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
