# Generated by Django 3.2 on 2022-08-08 19:46

from django.db import migrations


def set_price_in_order(apps, schema_editor):
    OrderElements = apps.get_model('foodcartapp', 'OrderElements')
    order_elements_set = OrderElements.objects.all()
    order_elements_iterator = order_elements_set.iterator()
    for order_element in order_elements_iterator:
        order_element.price_in_order = order_element.product.price * order_element.quantity
        order_element.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0042_orderelements_price_in_order'),
    ]

    operations = [
        migrations.RunPython(set_price_in_order),
    ]
