# Generated by Django 3.2 on 2022-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220808_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Подтверждение', 'Подтверждение'), ('Готовится', 'Готовится'), ('Доставка', 'Доставка'), ('Выполнен', 'Выполнен')], db_index=True, default='Подтверждение', max_length=13, verbose_name='Статус заказа'),
        ),
    ]
