# Generated by Django 3.2 on 2022-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20220810_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('Электронно', 'Электронно'), ('Наличностью', 'Наличностью')], db_index=True, max_length=11, null=True, verbose_name='Способ оплаты'),
        ),
    ]
