# Generated by Django 3.2 on 2022-08-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('CASH', 'Электронно'), ('CARD', 'Наличностью')], db_index=True, max_length=4, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UP', 'Необработанный'), ('IW', 'Готовится'), ('ID', 'Доставка'), ('DN', 'Выполнен')], db_index=True, default='Необработанный', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
